repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --all --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: npx prettier --check
        language: system
        files: \.(ts|js|json|md)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
